services:
  bagle:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: bagle-in-docker:0.1
    container_name: bagle_container
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - ../data:/data
